In [3]:
import torch
from torch import nn
import numpy as np
import pandas as pd

In [4]:
companies_df = pd.read_csv('companies_sorted.csv')

In [5]:
companies_df.head()

Unnamed: 0                       name         domain  year founded  \
0     5872184                        ibm        ibm.com        1911.0   
1     4425416  tata consultancy services        tcs.com        1968.0   
2       21074                  accenture  accenture.com        1989.0   
3     2309813                    us army     goarmy.com        1800.0   
4     1558607                         ey         ey.com        1989.0   

                              industry size range  \
0  information technology and services     10001+   
1  information technology and services     10001+   
2  information technology and services     10001+   
3                             military     10001+   
4                           accounting     10001+   

                                 locality         country  \
0       new york, new york, united states   united states   
1              bombay, maharashtra, india           india   
2                 dublin, dublin, ireland         ireland   
3     alexandria, virginia, united states   united states   
4  london, greater london, united kingdom  united kingdom   

                                     linkedin url  current employee estimate  \
0                        linkedin.com/company/ibm                     274047   
1  linkedin.com/company/tata-consultancy-services                     190771   
2                  linkedin.com/company/accenture                     190689   
3                    linkedin.com/company/us-army                     162163   
4              linkedin.com/company/ernstandyoung                     158363   

   total employee estimate  
0                   716906  
1                   341369  
2                   455768  
3                   445958  
4                   428960

In [ ]:
#companies_df['name'][:1000].to_csv('companies_names_list.csv', index=False)

In [9]:
company_names = companies_df['name'][:1000].to_list()

In [10]:
len(company_names)

1000

In [39]:
print(' '.join(company_names))

ibm tata consultancy services accenture us army ey hewlett-packard cognizant technology solutions walmart microsoft at&t united states air force pwc wells fargo infosys deloitte citi bank of america jpmorgan chase & co. us navy amazon apple siemens oracle nokia education nationale capgemini wipro technologies hsbc google united states postal service mcdonald's corporation ericsson nhs boeing vodafone kaiser permanente ford motor company intel corporation department of veterans affairs cisco general motors pepsico target shell hcl technologies ups pfizer unilever nestlé unitedhealth group huawei technologies dell gsk honeywell sap schlumberger lockheed martin ayatama energi, trisco nusantara abb american center of krasnodar starbucks promobroker agente de seguros y de fianzas s a de c v morgan stanley the home depot independiente novartis johnson & johnson bp schneider electric state farm secretaría de educación pública dhl my home td ge philips ubs procter & gamble walgreens keller wil

In [11]:
len(''.join(company_names))

13915

In [23]:
all_chars = sorted(list(set(''.join(company_names))))

In [30]:
vocab_size = len(all_chars)

In [31]:
print(''.join(all_chars))

 "&'()+,-./1234abcdefghijklmnopqrstuvwxyz|®ãéëíóôúē


In [25]:
print(all_chars)

[' ', '"', '&', "'", '(', ')', '+', ',', '-', '.', '/', '1', '2', '3', '4', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '®', 'ã', 'é', 'ë', 'í', 'ó', 'ô', 'ú', 'ē']


In [26]:
stoi = {s:i for i,s in enumerate(all_chars)}

In [ ]:
stoi

In [28]:
itos = {i:s for i,s in enumerate(all_chars)}

In [32]:
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

In [34]:
for name in company_names:
    print(name)
    print(encode(name))
    print(decode(encode(name)))
    break

ibm
[23, 16, 27]
ibm


In [41]:
token_embedding = nn.Embedding(vocab_size, 32)

In [43]:
token = token_embedding(torch.tensor([23,16,27]))

In [44]:
token.shape

torch.Size([3, 32])

In [48]:
s_t = torch.stack((torch.tensor([23,16,27]), torch.tensor([23,16,27])))

In [49]:
s_t.shape

torch.Size([2, 3])

In [40]:
torch.arange(3)

tensor([0, 1, 2])

In [ ]:
class AddNorm(nn.Module):
    def __init__(self):
        pass
    def forward(self):
        pass


In [ ]:
class FeedForward(nn.Module):
    def __init__(self):
        pass
    def forward(self, x):
        pass

In [106]:
class MultiHeadAttention(nn.Module):
    def __init__(self):
        super(MultiHeadAttention, self).__init__()
        self.k = nn.Linear(32, 256)
        self.v = nn.Linear(32, 256)
        self.q = nn.Linear(32, 256)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x):
        k = self.k(x)
        v = self.v(x)
        q = self.q(x)

        k_t = k.transpose(-2,-1)

        score = (q@k_t)*(256**-0.5)

        score = self.softmax(score)

        scale_product = score @ v
        return scale_product




    

In [107]:
device = 'cpu'

class Encoder(nn.Module):
    def __init__(self):
        super(Encoder, self).__init__()
        self.token_embedding = nn.Embedding(vocab_size, 32)
        self.positional_embedding = nn.Embedding(vocab_size, 32)
        self.attention = MultiHeadAttention()
    def forward(self, x):
        B, T = x.shape
        tok_emb = self.token_embedding(x)
        pos_emb = self.positional_embedding(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.attention(x)
        return x
        

In [108]:
encoder_model = Encoder()

In [110]:
output = encoder_model(s_t)

In [111]:
output.shape

torch.Size([2, 3, 256])

In [54]:
token_embedding = nn.Embedding(vocab_size, 32)
positional_embedding = nn.Embedding(vocab_size, 32)

In [52]:
s_t.shape

torch.Size([2, 3])

In [50]:
tok_emb = token_embedding(s_t)

In [51]:
tok_emb.shape

torch.Size([2, 3, 32])

In [92]:
tok_emb

tensor([[[ 0.0046,  0.7505,  0.2035, -0.4211, -0.6388, -0.4264, -0.4218,
           1.1806,  0.6106, -0.6956, -0.0705,  0.8506, -0.8454,  0.2235,
          -0.9740,  0.8242, -0.6302, -0.9612, -0.8129, -0.3952, -2.5379,
           1.6012,  1.9479, -0.3859,  0.8988,  1.2202,  0.4016, -1.2533,
          -0.4792,  0.2088,  0.5764,  0.4761],
         [ 1.2787,  0.6821,  0.1316,  0.2017, -0.1356,  0.1750,  1.4072,
           0.9966,  1.9494,  0.2500,  1.2642, -0.1212,  1.2743, -0.2881,
          -1.3037, -0.5930, -0.1544,  0.7390,  0.7418, -0.3457, -1.2017,
          -0.5757, -0.4551, -0.0227,  0.3203, -0.2841, -1.1585,  2.1425,
           0.8435, -2.1409,  0.5537,  0.3262],
         [-1.9965,  0.6384,  0.0794, -0.1607,  1.4519,  1.2000,  0.7824,
          -0.9757, -0.2694, -0.3242,  0.9613,  1.4885,  0.1238,  0.2913,
          -0.5744, -1.7060, -0.2789, -1.4579, -0.3150,  0.0120,  1.1895,
          -1.4337, -1.1638,  0.9132, -0.6642,  0.7820,  1.2402, -0.4286,
           0.2548, -1.0330, -1

In [56]:
pos_emb = positional_embedding(torch.arange(s_t.shape[1]))

In [91]:
pos_emb

tensor([[ 0.7856,  0.3562,  1.3657,  1.5043,  1.4343, -0.9345, -1.0659,  0.9389,
         -0.6826,  0.8211, -1.0325,  0.9976, -1.4322,  1.3976, -0.2806,  1.3707,
          0.1050, -0.3740, -0.6313,  0.5737, -0.1931,  0.1040,  0.2545, -0.9184,
          0.6787,  1.0962,  0.3751, -0.7932,  1.1260,  1.0629,  0.8418,  0.1849],
        [ 2.0066, -0.4269, -1.0213, -0.6980,  0.0885,  1.1648,  0.7494, -2.4078,
          1.0039,  1.7696, -0.8426, -0.8318, -0.4504,  0.8640,  1.2991, -0.4292,
         -1.1728,  1.0519,  0.2715,  1.7247,  1.3487, -0.1793,  0.3564, -0.1641,
         -0.5973,  0.8126,  0.7207, -0.1425,  0.2975, -1.6622, -2.0338,  0.1040],
        [-0.7784,  0.3297, -0.2299,  0.0872,  1.5404,  0.5456,  0.1566, -1.1922,
         -0.5381, -2.6214,  0.3935, -1.0291,  0.0722, -0.2695,  0.6349, -0.7762,
         -1.8529, -0.7248, -0.1493, -0.5086,  2.1085, -0.0457,  0.9842, -0.4046,
         -1.0650,  0.5736,  0.6615,  0.1869,  0.6271, -2.3003,  0.3211, -0.2793]],
       grad_fn=<Embeddin

In [57]:
pos_emb.shape

torch.Size([3, 32])

In [60]:
a = torch.tensor([[1,2],[3,4]])

In [61]:
a.shape

torch.Size([2, 2])

In [62]:
b = torch.tensor([1,2])

In [63]:
b.shape

torch.Size([2])

In [64]:
a + b

tensor([[2, 4],
        [4, 6]])

In [58]:
input_1 = tok_emb + pos_emb

In [59]:
input_1.shape

torch.Size([2, 3, 32])

In [67]:
head_size = 256

In [69]:
k = nn.Linear(32, head_size)(input_1)
v = nn.Linear(32, head_size)(input_1)
q = nn.Linear(32, head_size)(input_1)


In [76]:
k.shape

torch.Size([2, 3, 256])

In [73]:
q.shape

torch.Size([2, 3, 256])

In [80]:
k_t = k.transpose(-2,-1)

In [81]:
k_t.shape

torch.Size([2, 256, 3])

In [83]:
(q @ k_t).shape

torch.Size([2, 3, 3])

In [90]:
q @ k_t

tensor([[[  0.5213,  -4.0954,   7.1659],
         [  6.9738,  -7.9146, -20.1596],
         [ 28.7102, -10.6395, -17.2643]],

        [[  0.5213,  -4.0954,   7.1659],
         [  6.9738,  -7.9146, -20.1596],
         [ 28.7102, -10.6395, -17.2643]]], grad_fn=<UnsafeViewBackward0>)

In [87]:
scale_product = (q@k_t)/torch.sqrt(torch.Tensor([256]))

In [88]:
scale_product.shape

torch.Size([2, 3, 3])

In [89]:
scale_product

tensor([[[ 0.0326, -0.2560,  0.4479],
         [ 0.4359, -0.4947, -1.2600],
         [ 1.7944, -0.6650, -1.0790]],

        [[ 0.0326, -0.2560,  0.4479],
         [ 0.4359, -0.4947, -1.2600],
         [ 1.7944, -0.6650, -1.0790]]], grad_fn=<DivBackward0>)

In [95]:
attention_output = nn.Softmax(dim=-1)(scale_product)

In [97]:
attention_output

tensor([[[0.3064, 0.2296, 0.4641],
         [0.6338, 0.2499, 0.1163],
         [0.8757, 0.0749, 0.0495]],

        [[0.3064, 0.2296, 0.4641],
         [0.6338, 0.2499, 0.1163],
         [0.8757, 0.0749, 0.0495]]], grad_fn=<SoftmaxBackward0>)

In [96]:
attention_output.shape

torch.Size([2, 3, 3])